import { describe, expect, it } from 'vitest';
import { buildExportRows } from '../../src/lib/exportRows';
import type { Game, GameStats } from '../../src/types';

const game: Game = {
  id: 7,
  date: '2026-04-21',
  team_home: 'Альфа',
  team_away: 'Бета',
  color_home: 'red',
  color_away: 'blue',
  hammer_first_end: 'home',
  max_ends: 8,
  status: 'finished',
  created_at: '2026-04-21T09:00:00Z',
  score_home: 5,
  score_away: 3,
};

const stats: GameStats = {
  home: {
    avg: 71,
    shot_count: 16,
    players: [
      {
        position: 1,
        avg: 75,
        shot_count: 4,
        draw_avg: 75,
        takeout_avg: 0,
        inturn_avg: 75,
        outturn_avg: 0,
        inturn_draw_avg: 75,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 4,
        takeout_count: 0,
        draw_in_count: 4,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
      {
        position: 2,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
      {
        position: 3,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
      {
        position: 4,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
    ],
  },
  away: {
    avg: 63,
    shot_count: 16,
    players: [
      {
        position: 1,
        avg: 50,
        shot_count: 2,
        draw_avg: 0,
        takeout_avg: 50,
        inturn_avg: 50,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 50,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 2,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 2,
        takeout_out_count: 0,
      },
      {
        position: 2,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
      {
        position: 3,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
      {
        position: 4,
        avg: 0,
        shot_count: 0,
        draw_avg: 0,
        takeout_avg: 0,
        inturn_avg: 0,
        outturn_avg: 0,
        inturn_draw_avg: 0,
        inturn_takeout_avg: 0,
        outturn_draw_avg: 0,
        outturn_takeout_avg: 0,
        draw_count: 0,
        takeout_count: 0,
        draw_in_count: 0,
        draw_out_count: 0,
        takeout_in_count: 0,
        takeout_out_count: 0,
      },
    ],
  },
};

describe('buildExportRows', () => {
  it('builds detailed rows for each game/team/position/shot type/turn combination', () => {
    const rows = buildExportRows([{ game, stats }]);

    expect(rows).toContainEqual({
      'Игра': 'Альфа — Бета | 21.04.2026',
      'Команда': 'Альфа',
      'Позиция': 'Лид',
      'Тип броска': 'Draw',
      'Вращение': 'In-turn',
      'Количество': 4,
      '%': 75,
      'Вес для среднего': 300,
    });

    expect(rows).toContainEqual({
      'Игра': 'Альфа — Бета | 21.04.2026',
      'Команда': 'Бета',
      'Позиция': 'Лид',
      'Тип броска': 'Take',
      'Вращение': 'In-turn',
      'Количество': 2,
      '%': 50,
      'Вес для среднего': 100,
    });
  });

  it('keeps zero-count combinations as rows for maximum detail', () => {
    const rows = buildExportRows([{ game, stats }]);

    expect(rows).toContainEqual({
      'Игра': 'Альфа — Бета | 21.04.2026',
      'Команда': 'Альфа',
      'Позиция': 'Лид',
      'Тип броска': 'Take',
      'Вращение': 'Out-turn',
      'Количество': 0,
      '%': 0,
      'Вес для среднего': 0,
    });
  });
});
